"""esquema inicial

Revision ID: 0001
Revises:
Create Date: 2026-10-02 11:55:07.968985
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bots",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("strategy", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PAUSED",
                "RETIRED",
                name="botstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_bots")),
        sa.UniqueConstraint("name", name=op.f("uq_bots_name")),
    )
    op.create_table(
        "brokers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "server_utc_offset_policy",
            sa.String(length=32),
            server_default="EA_REPORTED",
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brokers")),
        sa.UniqueConstraint("name", name=op.f("uq_brokers_name")),
    )
    op.create_table(
        "data_splits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "scope", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("train_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("validation_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("oos_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "frozen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "train_end < validation_end AND validation_end < oos_end",
            name=op.f("ck_data_splits_ordered"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_splits")),
    )
    op.create_table(
        "feature_definitions",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.Column("group", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=True),
        sa.Column("formula_doc", sa.Text(), nullable=False),
        sa.Column("null_policy", sa.Text(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", "version", name=op.f("pk_feature_definitions")),
    )
    op.create_table(
        "hypotheses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "condition_spec",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "scope", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PROPOSED",
                "TESTING",
                "VALIDATED",
                "REJECTED",
                "DECAYED",
                name="hypothesisstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="PROPOSED",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hypotheses")),
    )
    op.create_table(
        "news_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("impact", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_events")),
        sa.UniqueConstraint(
            "source",
            "time_utc",
            "currency",
            "title",
            name=op.f("uq_news_events_source_time_utc_currency_title"),
        ),
    )
    op.create_index("ix_news_events_time", "news_events", ["time_utc"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("broker_id", sa.UUID(), nullable=False),
        sa.Column("login", sa.BigInteger(), nullable=False),
        sa.Column("server", sa.String(length=128), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(
                "DEMO",
                "REAL",
                "CONTEST",
                name="accounttype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "margin_mode",
            sa.Enum(
                "HEDGING",
                "NETTING",
                "EXCHANGE",
                name="marginmode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("leverage", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"], ["brokers.id"], name=op.f("fk_accounts_broker_id_brokers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("server", "login", name=op.f("uq_accounts_server_login")),
    )
    op.create_table(
        "bot_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("main_timeframe", sa.String(length=8), nullable=False),
        sa.Column(
            "params", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("params_hash", sa.String(length=64), nullable=True),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("changelog", sa.Text(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version ~ '^\\d+\\.\\d+\\.\\d+(-[0-9A-Za-z.-]+)?$'",
            name=op.f("ck_bot_versions_semver"),
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.bot_id"], name=op.f("fk_bot_versions_bot_id_bots")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_versions")),
        sa.UniqueConstraint("bot_id", "version", name=op.f("uq_bot_versions_bot_id_version")),
    )
    op.create_index(op.f("ix_bot_versions_bot_id"), "bot_versions", ["bot_id"], unique=False)
    op.create_table(
        "pattern_tests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hypothesis_id", sa.UUID(), nullable=False),
        sa.Column("split_id", sa.UUID(), nullable=False),
        sa.Column(
            "segment",
            sa.Enum(
                "TRAIN",
                "VALIDATION",
                "OOS",
                "FORWARD",
                name="splitsegment",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("win_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("expectancy", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("profit_factor", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("ci_low", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("ci_high", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("p_value", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("p_adjusted", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("tests_in_family", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("n >= 0", name=op.f("ck_pattern_tests_n_non_negative")),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["hypotheses.id"],
            name=op.f("fk_pattern_tests_hypothesis_id_hypotheses"),
        ),
        sa.ForeignKeyConstraint(
            ["split_id"], ["data_splits.id"], name=op.f("fk_pattern_tests_split_id_data_splits")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pattern_tests")),
    )
    op.create_index(
        op.f("ix_pattern_tests_hypothesis_id"), "pattern_tests", ["hypothesis_id"], unique=False
    )
    op.create_table(
        "price_bars",
        sa.Column("broker_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("bar_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("high", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("low", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("close", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("tick_volume", sa.BigInteger(), nullable=False),
        sa.Column("spread", sa.Integer(), nullable=True),
        sa.CheckConstraint("high >= low", name=op.f("ck_price_bars_high_low")),
        sa.CheckConstraint(
            "high >= open AND high >= close", name=op.f("ck_price_bars_high_bounds")
        ),
        sa.CheckConstraint("low <= open AND low <= close", name=op.f("ck_price_bars_low_bounds")),
        sa.ForeignKeyConstraint(
            ["broker_id"], ["brokers.id"], name=op.f("fk_price_bars_broker_id_brokers")
        ),
        sa.PrimaryKeyConstraint(
            "broker_id", "symbol", "timeframe", "bar_time", name=op.f("pk_price_bars")
        ),
    )
    op.create_table(
        "account_snapshots",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("balance", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("equity", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("margin", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("free_margin", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_account_snapshots_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("account_id", "ts", name=op.f("pk_account_snapshots")),
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bot_version_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("magic_number", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at > started_at", name=op.f("ck_deployments_dates")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_deployments_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["bot_version_id"],
            ["bot_versions.id"],
            name=op.f("fk_deployments_bot_version_id_bot_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployments")),
    )
    op.create_index(op.f("ix_deployments_account_id"), "deployments", ["account_id"], unique=False)
    op.create_index(
        op.f("ix_deployments_bot_version_id"), "deployments", ["bot_version_id"], unique=False
    )
    op.create_index(
        "uq_deployments_active_magic",
        "deployments",
        ["account_id", "magic_number", "symbol"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("base_version_id", sa.UUID(), nullable=False),
        sa.Column("candidate_version_id", sa.UUID(), nullable=True),
        sa.Column("hypothesis_id", sa.UUID(), nullable=True),
        sa.Column("change_description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "RUNNING",
                "COMPLETED",
                "ABANDONED",
                name="experimentstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("conclusion", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_version_id"],
            ["bot_versions.id"],
            name=op.f("fk_experiments_base_version_id_bot_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_version_id"],
            ["bot_versions.id"],
            name=op.f("fk_experiments_candidate_version_id_bot_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["hypotheses.id"],
            name=op.f("fk_experiments_hypothesis_id_hypotheses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiments")),
        sa.UniqueConstraint("code", name=op.f("uq_experiments_code")),
    )
    op.create_table(
        "terminals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("host_description", sa.String(length=256), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_terminals_account_id_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terminals")),
        sa.UniqueConstraint("name", name=op.f("uq_terminals_name")),
    )
    op.create_index(op.f("ix_terminals_account_id"), "terminals", ["account_id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "WARNING",
                "CRITICAL",
                name="alertseverity",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("bot_version_id", sa.UUID(), nullable=True),
        sa.Column("deployment_id", sa.UUID(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_version_id"],
            ["bot_versions.id"],
            name=op.f("fk_alerts_bot_version_id_bot_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], name=op.f("fk_alerts_deployment_id_deployments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_rule"), "alerts", ["rule"], unique=False)
    op.create_table(
        "api_clients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("terminal_id", sa.UUID(), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["terminal_id"], ["terminals.id"], name=op.f("fk_api_clients_terminal_id_terminals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_clients")),
        sa.UniqueConstraint("key_prefix", name=op.f("uq_api_clients_key_prefix")),
    )
    op.create_index(
        op.f("ix_api_clients_terminal_id"), "api_clients", ["terminal_id"], unique=False
    )
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=True),
        sa.Column("bot_version_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("initial_deposit", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("report_file", sa.String(length=512), nullable=True),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("period_end > period_start", name=op.f("ck_backtest_runs_period")),
        sa.ForeignKeyConstraint(
            ["bot_version_id"],
            ["bot_versions.id"],
            name=op.f("fk_backtest_runs_bot_version_id_bot_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_backtest_runs_experiment_id_experiments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_runs")),
    )
    op.create_index(
        op.f("ix_backtest_runs_experiment_id"), "backtest_runs", ["experiment_id"], unique=False
    )
    op.create_table(
        "heartbeats",
        sa.Column("terminal_id", sa.UUID(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ea_version", sa.String(length=64), nullable=False),
        sa.Column("terminal_connected", sa.Boolean(), nullable=False),
        sa.Column("trade_allowed", sa.Boolean(), nullable=False),
        sa.Column(
            "info", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["terminal_id"], ["terminals.id"], name=op.f("fk_heartbeats_terminal_id_terminals")
        ),
        sa.PrimaryKeyConstraint("terminal_id", "ts", name=op.f("pk_heartbeats")),
    )
    op.create_table(
        "raw_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("terminal_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("schema_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSED",
                "FAILED",
                "IGNORED",
                name="raweventstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("attempts", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["terminal_id"], ["terminals.id"], name=op.f("fk_raw_events_terminal_id_terminals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_events")),
        sa.UniqueConstraint(
            "terminal_id", "idempotency_key", name=op.f("uq_raw_events_terminal_id_idempotency_key")
        ),
    )
    op.create_index(
        "ix_raw_events_pending",
        "raw_events",
        ["terminal_id", "sent_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "trades",
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("deployment_id", sa.UUID(), nullable=True),
        sa.Column("bot_version_id", sa.UUID(), nullable=True),
        sa.Column("position_id", sa.BigInteger(), nullable=False),
        sa.Column("magic_number", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "BUY",
                "SELL",
                name="direction",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("order_type", sa.String(length=32), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "LIVE",
                "DEMO",
                "BACKTEST",
                "FORWARD",
                "IMPORTED",
                name="tradesource",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                name="tradestatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column("comment", sa.String(length=64), nullable=True),
        sa.Column("symbol_digits", sa.SmallInteger(), nullable=True),
        sa.Column("symbol_point", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("tick_size", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("tick_value", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("contract_size", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("entry_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("initial_sl", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("initial_tp", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("initial_volume", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("max_volume", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("risk_amount", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("risk_percent", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("balance_at_entry", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("close_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("gross_profit", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("commission", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("swap", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("net_profit", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("points", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "exit_reason",
            sa.Enum(
                "SL",
                "TP",
                "MANUAL",
                "EXPERT",
                "STOP_OUT",
                "MIXED",
                "UNKNOWN",
                name="exitreason",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("mfe_points", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("mae_points", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("max_floating_profit", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("max_floating_drawdown", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column(
            "excursion_source",
            sa.Enum(
                "EA_TICKS",
                "M1_BARS",
                name="excursionsource",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("reentry_of_trade_id", sa.UUID(), nullable=True),
        sa.Column(
            "data_quality",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = 'OPEN' OR close_time IS NOT NULL",
            name=op.f("ck_trades_closed_has_close_time"),
        ),
        sa.CheckConstraint(
            "close_time IS NULL OR close_time >= entry_time", name=op.f("ck_trades_time_order")
        ),
        sa.CheckConstraint("initial_volume > 0", name=op.f("ck_trades_positive_volume")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_trades_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["bot_version_id"],
            ["bot_versions.id"],
            name=op.f("fk_trades_bot_version_id_bot_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], name=op.f("fk_trades_deployment_id_deployments")
        ),
        sa.ForeignKeyConstraint(
            ["reentry_of_trade_id"],
            ["trades.trade_id"],
            name=op.f("fk_trades_reentry_of_trade_id_trades"),
        ),
        sa.PrimaryKeyConstraint("trade_id", name=op.f("pk_trades")),
        sa.UniqueConstraint(
            "account_id", "position_id", name=op.f("uq_trades_account_id_position_id")
        ),
    )
    op.create_index(
        "ix_trades_open",
        "trades",
        ["account_id"],
        unique=False,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.create_index("ix_trades_symbol_entry", "trades", ["symbol", "entry_time"], unique=False)
    op.create_index(
        "ix_trades_version_entry", "trades", ["bot_version_id", "entry_time"], unique=False
    )
    op.create_table(
        "trade_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("analysis_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "WIN",
                "LOSS",
                "BREAKEVEN",
                name="outcome",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.trade_id"], name=op.f("fk_trade_analyses_trade_id_trades")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_analyses")),
        sa.UniqueConstraint(
            "trade_id", "analysis_version", name=op.f("uq_trade_analyses_trade_id_analysis_version")
        ),
    )
    op.create_index(
        op.f("ix_trade_analyses_trade_id"), "trade_analyses", ["trade_id"], unique=False
    )
    op.create_table(
        "trade_dna",
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("feature_set_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "EA",
                "SERVER",
                name="dataorigin",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("data_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trend_m1", sa.SmallInteger(), nullable=True),
        sa.Column("trend_m5", sa.SmallInteger(), nullable=True),
        sa.Column("trend_m15", sa.SmallInteger(), nullable=True),
        sa.Column("trend_h1", sa.SmallInteger(), nullable=True),
        sa.Column("trend_h4", sa.SmallInteger(), nullable=True),
        sa.Column("trend_d1", sa.SmallInteger(), nullable=True),
        sa.Column("ema20", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("ema50", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("ema200", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("rsi", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("atr", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("roc", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("adx", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("market_structure", sa.String(length=16), nullable=True),
        sa.Column("last_swing_high", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("last_swing_low", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("bos_recent", sa.Boolean(), nullable=True),
        sa.Column("choch_recent", sa.Boolean(), nullable=True),
        sa.Column("is_range", sa.Boolean(), nullable=True),
        sa.Column("liquidity_sweep", sa.Boolean(), nullable=True),
        sa.Column("equal_highs", sa.Boolean(), nullable=True),
        sa.Column("equal_lows", sa.Boolean(), nullable=True),
        sa.Column("dist_prev_high_points", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("dist_prev_low_points", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("fvg_present", sa.Boolean(), nullable=True),
        sa.Column("fvg_direction", sa.SmallInteger(), nullable=True),
        sa.Column("fvg_size_points", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("fvg_distance_points", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("ob_present", sa.Boolean(), nullable=True),
        sa.Column("ob_direction", sa.SmallInteger(), nullable=True),
        sa.Column("ob_distance_points", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("spread_points", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("recent_range_points", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("relative_volatility", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("weekday", sa.SmallInteger(), nullable=True),
        sa.Column("hour_utc", sa.SmallInteger(), nullable=True),
        sa.Column("session_asia", sa.Boolean(), nullable=True),
        sa.Column("session_london", sa.Boolean(), nullable=True),
        sa.Column("session_newyork", sa.Boolean(), nullable=True),
        sa.Column("news_nearby", sa.Boolean(), nullable=True),
        sa.Column("minutes_to_news", sa.Integer(), nullable=True),
        sa.Column("news_impact", sa.String(length=16), nullable=True),
        sa.Column("news_type", sa.String(length=64), nullable=True),
        sa.Column(
            "extra", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "null_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.trade_id"], name=op.f("fk_trade_dna_trade_id_trades")
        ),
        sa.PrimaryKeyConstraint("trade_id", "feature_set_version", name=op.f("pk_trade_dna")),
    )
    op.create_table(
        "trade_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("raw_event_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "TRADE_OPENED",
                "SL_MODIFIED",
                "TP_MODIFIED",
                "PARTIAL_CLOSE",
                "REENTRY",
                "POSITION_INCREASED",
                "POSITION_DECREASED",
                "TRADE_CLOSED",
                name="tradeeventtype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("event_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_time_server", sa.DateTime(), nullable=True),
        sa.Column("price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("volume", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("sl", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("tp", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("deal_ticket", sa.BigInteger(), nullable=True),
        sa.Column("order_ticket", sa.BigInteger(), nullable=True),
        sa.Column("profit", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("commission", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("swap", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("is_inferred", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "extra", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_event_id"],
            ["raw_events.id"],
            name=op.f("fk_trade_events_raw_event_id_raw_events"),
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.trade_id"], name=op.f("fk_trade_events_trade_id_trades")
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_trade_events")),
    )
    op.create_index(
        "ix_trade_events_trade_time", "trade_events", ["trade_id", "event_time_utc"], unique=False
    )
    op.create_index(
        "uq_trade_events_trade_id_deal_ticket",
        "trade_events",
        ["trade_id", "deal_ticket"],
        unique=True,
        postgresql_where=sa.text("deal_ticket IS NOT NULL"),
    )
    op.create_table(
        "analysis_findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "FACT",
                "HYPOTHESIS",
                name="findingkind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("hypothesis_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["trade_analyses.id"],
            name=op.f("fk_analysis_findings_analysis_id_trade_analyses"),
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["hypotheses.id"],
            name=op.f("fk_analysis_findings_hypothesis_id_hypotheses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_findings")),
    )
    op.create_index(
        op.f("ix_analysis_findings_analysis_id"), "analysis_findings", ["analysis_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_findings_analysis_id"), table_name="analysis_findings")
    op.drop_table("analysis_findings")
    op.drop_index(
        "uq_trade_events_trade_id_deal_ticket",
        table_name="trade_events",
        postgresql_where=sa.text("deal_ticket IS NOT NULL"),
    )
    op.drop_index("ix_trade_events_trade_time", table_name="trade_events")
    op.drop_table("trade_events")
    op.drop_table("trade_dna")
    op.drop_index(op.f("ix_trade_analyses_trade_id"), table_name="trade_analyses")
    op.drop_table("trade_analyses")
    op.drop_index("ix_trades_version_entry", table_name="trades")
    op.drop_index("ix_trades_symbol_entry", table_name="trades")
    op.drop_index(
        "ix_trades_open", table_name="trades", postgresql_where=sa.text("status = 'OPEN'")
    )
    op.drop_table("trades")
    op.drop_index(
        "ix_raw_events_pending",
        table_name="raw_events",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("raw_events")
    op.drop_table("heartbeats")
    op.drop_index(op.f("ix_backtest_runs_experiment_id"), table_name="backtest_runs")
    op.drop_table("backtest_runs")
    op.drop_index(op.f("ix_api_clients_terminal_id"), table_name="api_clients")
    op.drop_table("api_clients")
    op.drop_index(op.f("ix_alerts_rule"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_terminals_account_id"), table_name="terminals")
    op.drop_table("terminals")
    op.drop_table("experiments")
    op.drop_index(
        "uq_deployments_active_magic",
        table_name="deployments",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_index(op.f("ix_deployments_bot_version_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_account_id"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_table("account_snapshots")
    op.drop_table("price_bars")
    op.drop_index(op.f("ix_pattern_tests_hypothesis_id"), table_name="pattern_tests")
    op.drop_table("pattern_tests")
    op.drop_index(op.f("ix_bot_versions_bot_id"), table_name="bot_versions")
    op.drop_table("bot_versions")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_index("ix_news_events_time", table_name="news_events")
    op.drop_table("news_events")
    op.drop_table("hypotheses")
    op.drop_table("feature_definitions")
    op.drop_table("data_splits")
    op.drop_table("brokers")
    op.drop_table("bots")
    # ### end Alembic commands ###
